YALO_RUN=./yalo.exe

yalotest: build
	$(YALO_RUN) lint . $(YALO_FINAL_ARGS)

yalofind: build
	$(YALO_RUN) lint -L yalo_plugin_FIND --skip-config-warnings -w FIND $(YALO_FINAL_ARGS)

yalo_sarif: build
	$(YALO_RUN) lint --message-format sarif > _yalo/test.sarif

